apiVersion: v1
kind: PersistentVolume
metadata:
  name: frontend-pv
  labels:
    type: local
spec:
  storageClassName: frontend-pv
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/app"