apiVersion: v1
kind: PersistentVolume
metadata:
  name: kratos-pv
  labels:
    type: local
spec:
  storageClassName: kratos-pv
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/contrib/quickstart/kratos/"