apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.network/intranet: "true"
    io.kompose.service: oathkeeper
  name: oathkeeper
spec:
  containers:
    - args:
        - serve
        - proxy
        - -c
        - /etc/config/oathkeeper/.oathkeeper.yml
      env:
        - name: LOG_LEVEL
          value: debug
      image: oryd/oathkeeper:v0.38.1
      name: oathkeeper
      ports:
        - containerPort: 4455
        - containerPort: 4456
      resources: {}
      volumeMounts:
        - mountPath: /etc/config/oathkeeper
          name: oathkeeper-claim0
  restartPolicy: OnFailure
  volumes:
    - name: oathkeeper-claim0
      persistentVolumeClaim:
        claimName: oathkeeper-claim0
status: {}
