apiVersion: v1
kind: PersistentVolume
metadata:
  name: opa-pv
  labels:
    type: local
spec:
  storageClassName: opa-pv
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/policies/frontend"