name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install dependencies
      run: go install github.com/gobuffalo/packr/v2/packr2
      
    - name: Build
      run: |
        packr2
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on go build -o app .
        packr2 clean

    - name: Docker Login
      uses: docker/login-action@v1.14.1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
   
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1.6.0

    - name: Build and push Docker images
      uses: docker/build-push-action@v2.9.0
      with:
        file: ./dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/kratos-frontend-go
